### ISSUE TITLE
Release 0.2.0 ?

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/cmweather#23]
Is there bandwidth to create a release for the latest additions? I'd be able to help beginning of November.

**Comment by zssherman** [comment]
@kmuehlbauer Hello! I can get a release out today for it, and get those changes going

**Comment by kmuehlbauer** [comment]
Great, @zssherman! Thanks!

**Comment by zssherman** [comment]
@kmuehlbauer The github release is out, just waiting now on pypi and conda-forge to pick it up.

**Comment by mgrover1** [comment]
Closing this out now that the releases are available!
